name: Deploy to AWS EC2

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_EC2_KEY }}

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Copy build files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} 'mkdir -p /home/${{ secrets.AWS_EC2_USER }}/frontend-app'
          scp -o StrictHostKeyChecking=no -r build/* ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/frontend-app

      - name: Configure Nginx and restart
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            sudo rsync -av --delete /home/${{ secrets.AWS_EC2_USER }}/frontend-app/ /var/www/html/
            sudo systemctl restart nginx
          EOF

      - name: Install dependencies and restart app
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd /home/${{ secrets.AWS_EC2_USER }}/frontend-app
            npm install
            pm2 restart all || pm2 start src/index.ts --name "my-app" --interpreter ./node_modules/.bin/ts-node
          EOF
